package Pojos;
// Generated 04/07/2015 11:31:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private double precioTotal;
     private String estado;
     private Set pedidos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Factura(double precioTotal, String estado, Set pedidos) {
       this.precioTotal = precioTotal;
       this.estado = estado;
       this.pedidos = pedidos;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


