package Pojos;
// Generated 04/07/2015 11:31:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Categoria categoria;
     private String descripcion;
     private Double precio;
     private String marca;
     private Integer stock;
     private char estado;
     private Set detalles = new HashSet(0);
     private Set imagens = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, char estado) {
        this.categoria = categoria;
        this.estado = estado;
    }
    public Producto(Categoria categoria, String descripcion, Double precio, String marca, Integer stock, char estado, Set detalles, Set imagens) {
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.precio = precio;
       this.marca = marca;
       this.stock = stock;
       this.estado = estado;
       this.detalles = detalles;
       this.imagens = imagens;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }




}


